#!/bin/bash
status=$(/usr/share/i3blocks/volume)
muted="MUTE"
if [[ $status == $muted ]]
then
    echo "<span bgcolor='#FFFC1D' fgcolor='#FF254B' font='10'>🔇</span><span bgcolor='#FFFC1D' fgcolor='#FF254b'> MUTED </span>"
else
    echo "<span bgcolor='#FFFC1D' fgcolor='#8E2DFF'> $status </span>"
fi
