#!/bin/bash
status=$(sudo iwgetid -r)
GRN='\033[0;32m'
NC='\033[0;0m'
RED='\033[0;31m'

if [[ ! $status ]]
then
    echo "<span bgcolor='#3153FF' fgcolor='#A54242'>  Down </span>"
    printf "\n"
else
    echo "<span bgcolor='#3153FF' fgcolor='#24FF36'>  ${status} </span>"
    printf "\n"  
fi

case $BLOCK_BUTTON in
    1) nm-applet;;
esac
