#!/bin/bash

#Update Sources
cp sources.list /etc/apt/sources.list;
aptitude update;
apt-get dist-upgrade;
cp /home/cshansen/Documents/Settings/i3blocks /usr/share/

#Nvidia Drivers
aptitude install linux-headers-3.16.0-4-amd64 build-essential;
echo deb http://repo.steampowered.com/steamos brewmaster main contrib non-free > /etc/apt/sources.list.d/steamos.list;
aptitude update;
aptitude install -t brewmaster libegl1-nvidia:amd64 libgl1-nvidia-glx:amd64 libgl1-nvidia-glx:i386 libgl1-nvidia-glx-i386 libgles1-nvidia:amd64 libgles2-nvidia:amd64 libnvidia-eglcore:amd64 libnvidia-ml1:amd64 libxnvctrl0 nvidia-alternative nvidia-driver nvidia-driver-bin nvidia-kernel-dkms nvidia-modprobe nvidia-settings nvidia-vdpau-driver:amd64 xserver-xorg-video-nvidia;
rm -r /etc/apt/sources.list.d/*;

#General Utilities
apt-get install sudo;
useradd -g cshansen sudo;
apt-get install terminator;
apt-get install arandr;
apt-get install nitrogen;
apt-get install feh;
apt-get -f install;
apt-get install python-pip;
apt-get install git;
apt-get install krita;
apt-get install scrot;
apt-get install zip;
apt-get install unzip;

#Fonts
apt-get install fonts-font-awesome;
apt-get install unifont;
fc-cache -f -v;

#Window manager
apt-get install i3;
apt-get install i3blocks;
cp /home/cshansen/Documents/Settings/i3blocks /usr/share/
apt-get install lightdm;
dpkg-reconfigure lightdm;

#Editors
apt-get install emacs;
apt-get install vim;
apt-get install eclipse;
apt-get install texlive-full;

#Music
apt-get install mpd;
apt-get install ncmpcpp;
apt-get install pavucontrol;

#Internet
apt-get install chromium;
aptitude install pepperflashplugin-nonfree browser-plugin-freshplayer-pepperflash;

#Local Packages
dpkg -i sublime-text_build-3083_amd64.deb;
dpkg -i usbmount_0.0.14.1_all.deb;
dpkg -i steam_lastest.deb;
sudo apt-get install libc6*
apt-get install -f;


echo "ALL DONE!";
